pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                sh '''
                    cd Week5/activity
                    python3 -m venv myenv
                    myenv/bin/pip install -r requirements.txt
                '''
            }
        }

        stage('Test') {
            steps {
                sh '''
                    cd Week5/activity
                    myenv/bin/pytest
                '''
            }
        }

        stage('Validation') {
            steps {
                sh '''
                    cd Week5/activity
                    python3 -m py_compile app.py test_app.py
                '''
            }
        }
    }
}