pipeline {
	agent any

	stages {
		stage('Checkout') {
			steps {
				checkout scm
			}
		}
		stage('Build') {
			sh '''
			python3 -m venv myenv
			source myenv/bin/activate
			pip install -r requirements.txt
			'''
		}
		stage('Test') {
			shh '''
			pip install pytest
			pytest
			'''
		}
	}


}
