pipeline {
	agent any

	stages {

		stage('Checkout') {
			steps {
				checkout scm
			}
		}

		stage('Build') {
			steps {
				sh '''
                    python3 -m venv myenv
                    myenv/bin/pip install -r requirements.txt
                '''
			}
		}

		stage('Test') {
			steps {
				sh '''
                    myenv/bin/pytest
                '''
			}
		}
	}
}