pipeline {
    agent any

    environment {
    IMAGE_NAME = 'YOUR_DOCKERHUB_USERNAME/jenkins-cicd-app'
    IMAGE_TAG = "build-${BUILD_NUMBER}"
}

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                dir('Week9/Task') {
                    echo 'Creating virtual environment and installing dependencies...'
                    sh 'python3 -m venv venv'
                    sh 'venv/bin/pip install -r requirements.txt'
                }
            }
        }

        stage('Test') {
            steps {
                dir('Week9/Task') {
                    echo 'Running automated tests...'
                    sh 'venv/bin/pytest app/test_app.py -v'
                }
            }
        }

        stage('Package') {
            steps {
                dir('Week9/Task') {
                    echo 'Packaging application...'
                    sh 'tar -czf app-package.tar.gz app requirements.txt'
                }
            }
        }

        stage('Docker Build') {
            steps {
                dir('Week9/Task') {
                    echo "Building Docker image: ${IMAGE_NAME}:${IMAGE_TAG}"
                    sh 'docker build -t ${IMAGE_NAME}:${IMAGE_TAG} .'
                    sh 'docker tag ${IMAGE_NAME}:${IMAGE_TAG} ${IMAGE_NAME}:latest'
                }
            }
        }
	stage('Docker Push') {
    steps {
        withCredentials([usernamePassword(
            credentialsId: 'dockerhub-creds',
            usernameVariable: 'DOCKER_USERNAME',
            passwordVariable: 'DOCKER_PASSWORD'
        )]) {
            sh '''
                echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
                docker push ${IMAGE_NAME}:${IMAGE_TAG}
                docker push ${IMAGE_NAME}:latest
                docker logout
            '''
        }
    }
}
        
    }

    post {
        success {
            echo 'Jenkins CI/CD pipeline completed successfully!'
        }
        failure {
            echo 'Pipeline failed. Check the console output.'
        }
    }
}
