---
- name: Configure ubuntu system
  hosts: local
  become: yes

  tasks:

    - name: Install Apache
      apt:
        name: apache2
        state: present
        update_cache: true

    - name: create user
      user:
        name: dev
        state: present
        shell: /bin/bash

    - name: start apache service
      service:
        name: apache2
        state: started
        enabled: true
    - name: create a custom index.html
      copy:
        dest: /var/www/html/index.html
        content: "<h3>This is the week6 task</h3><br><p>Ansible testing</p>"

